name: Valida Build & Test

on:
  push:
    branches:
      - develop 
jobs:
  valida-backend:
    name: Validação Backend
    uses: ./.github/workflows/valida-backend.yaml

  valida-frontend:
    name: Validação Frontend
    uses: ./.github/workflows/valida-frontend.yaml